### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by chinonso098** [james-pre/utilium#1]
I pulled the latest build of ZenFS (1.0.4) and I started getting these errors below

<img width="1851" alt="Screenshot 2024-10-10 at 9 50 20 AM" src="https://github.com/user-attachments/assets/ce8062cb-bf97-42df-aef1-6b9028881754">

**Comment by james-pre** [comment]
@chinonso098,

What is the output of `npm ls` and what are the contents of your `tsconfig.json`? (Please paste into code blocks)

**Comment by chinonso098** [comment]
npm ls   output

cheetah-os@2.7.31 /Users/chinonsomaduakolam/Documents/Dev/local_git/CheetahOS
├── @angular-builders/custom-webpack@18.0.0
├── @angular-devkit/build-angular@18.2.8
├── @angular-eslint/builder@18.3.1
├── @angular-eslint/eslint-plugin-template@18.3.1
├── @angular-eslint/eslint-plugin@18.3.1
├── @angular-eslint/schematics@18.3.1
├── @angular-eslint/template-parser@18.3.1
├── @angular/animations@18.2.8
├── @angular/cdk@18.2.8
├── @angular/cli@18.0.7
├── @angular/common@18.2.8
├── @angular/compiler-cli@18.2.8
├── @angular/compiler@18.2.8
├── @angular/core@18.2.8
├── @angular/forms@18.2.8
├── @angular/platform-browser-dynamic@18.2.8
├── @angular/platform-browser@18.2.8
├── @angular/router@18.2.8
├── @types/filesystem@0.0.32
├── @types/ini@1.3.34
├── @types/jest@28.1.8
├── @types/three@0.125.2
├── @typescript-eslint/eslint-plugin@5.62.0
├── @typescript-eslint/parser@5.62.0
├── @zenfs/core@1.0.4
├── @zenfs/dom@0.2.16
├── angular2-draggable@16.0.0
├── emulators-ui@0.73.9
├── emulators@0.73.9
├── eslint-config-google@0.14.0
├── eslint-plugin-angular@4.1.0
├── eslint@8.57.1
├── html-to-image@1.11.11
├── husky@8.0.3
├── ini@2.0.0
├── jest-preset-angular@14.2.4
├── jest@29.7.0
├── js-dos@7.5.0
├── karma-coverage@2.2.1
├── lint-staged@13.3.0
├── monaco-editor@0.49.0
├── ngx-monaco-editor-v2@18.0.1
├── notyf@3.10.0
├── path-browserify@1.0.1
├── rxjs@7.5.7
├── tslib@2.7.0
├── typescript@5.5.4
├── url@0.11.4
└── zone.js@0.14.10


tsconfig.json

```
{
  "compileOnSave": false,
  "compilerOptions": {
    "types" : ["filesystem","jest"],
    "paths": {
      "path":["./node_modules/path-browserify"],
      "url":["./node_modules/url"]
    },
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "noImplicitOverride": true,
    "noPropertyAccessFromIndexSignature": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "sourceMap": true,
    "declaration": false,
    "downlevelIteration": true,
    "experimentalDecorators": true,
    "importHelpers": true,
    "target": "es2022",
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "lib": [
      "es2022",
      "dom",
      "DOM.Iterable",
      "ESNext.Promise",
      "Decorators"
    ],
    "resolveJsonModule": true,
    "esModuleInterop": true
  },
  "angularCompilerOptions": {
    "enableI18nLegacyMessageIdFormat": false,
    "strictInjectionParameters": true,
    "strictInputAccessModifiers": true,
    "strictTemplates": true
  }
}

```

**Comment by james-pre** [comment]
@chinonso098,

Utilium uses the standard ES decorators from the stage 3 decorators proposal, not Typescript's legacy `experimentalDecorators`. What does compilation look like after removing `experimentalDecorators`? Additionally, you will need to include `ESNext.Decorators` to get typing for `Symbol.metadata`.

**Comment by chinonso098** [comment]
Ok, let me try that

**Comment by chinonso098** [comment]
I set  `experimentalDecorators: false`, and added  `ESNext.Decorators` and it compiled successfully. Thank you very much
